language: python
python:
  - "2.6"
before_script:
  - mysql -e 'create database snippets character set utf8;'
before_install:
  - git submodule update --init --recursive
  - pip install flake8
install:
  - pip install -r requirements/compiled.txt
  - pip install -r requirements/dev.txt
script: 
  - python manage.py test
  - flake8 snippets --exclude=*/migrations/* --exit-zero
