sudo: required
services:
  - docker
language: python
env:
  global:
    # NewRelic
    - NEWRELIC_US_WEST_STAGE_APPLICATION=snippets-stage-us-west
    - NEWRELIC_US_WEST_PROD_APPLICATION=snippets-prod-us-west
    - NEWRELIC_EU_WEST_STAGE_APPLICATION=snippets-stage-eu-west
    - NEWRELIC_EU_WEST_PROD_APPLICATION=snippets-prod-eu-west
    - NEWRELIC_US_WEST_ADMIN_APPLICATION=snippets-admin-us-west
    # Deis
    - DEIS_STAGE_APPLICATION=snippets-stage
    - DEIS_PROD_APPLICATION=snippets-prod
    - DEIS_PROD_ADMIN_APPLICATION=snippets-admin
    - DEIS_USERNAME=travis
    - DEIS_CONTROLLER_US_WEST=https://deis.us-west.moz.works
    - DEIS_CONTROLLER_EU_WEST=https://deis.eu-west.moz.works
    # Docker
    - DOCKER_REPOSITORY=mozorg/snippets
    - DOCKER_EMAIL="foo@example.com"
    - DOCKER_USERNAME="mozjenkins"
    # Django
    - DEBUG=False
    - DISABLE_SSL=True
    - ALLOWED_HOSTS=*
    - SECRET_KEY=foo
    - DATABASE_URL=mysql://root@db/snippets
    - SITE_URL=http://localhost:8000
    - CACHE_URL=dummy://
before_install:
  - docker --version
  - echo "ENV GIT_SHA ${TRAVIS_COMMIT}" >> Dockerfile
install:
  # Take advantage of docker caching by pulling previously built images.
  - docker pull ${DOCKER_REPOSITORY}:last_successful_build || true
  - docker pull ${DOCKER_REPOSITORY}:${TRAVIS_COMMIT} || true
  - docker build -t ${DOCKER_REPOSITORY}:${TRAVIS_COMMIT} --pull=true .
before_script:
  - env > .env
script:
  - docker run -d --name mariadb -e MYSQL_ALLOW_EMPTY_PASSWORD=yes -e MYSQL_DATABASE=snippets mariadb:10.0
  - docker run ${DOCKER_REPOSITORY}:${TRAVIS_COMMIT} flake8 snippets
  # Wait mysql to initialize.
  - docker run --link mariadb:db -e CHECK_PORT=3306 -e CHECK_HOST=db giorgos/takis
  - docker run --env-file .env --link mariadb:db ${DOCKER_REPOSITORY}:${TRAVIS_COMMIT} coverage run ./manage.py test
after_success:
  - sudo docker cp `docker ps -a -q | head -n 1`:/app /
  - sudo chown travis /app
  - cd /app
  - pip install codecov
  - codecov
deploy:
  - provider: script
    script: bin/deploy-travis.sh $DEIS_CONTROLLER_US_WEST $DEIS_STAGE_APPLICATION $NEWRELIC_US_WEST_STAGE_APPLICATION
    on:
      branch: master
      repo: mozilla/snippets-service
  - provider: script
    script: bin/deploy-travis.sh $DEIS_CONTROLLER_EU_WEST $DEIS_STAGE_APPLICATION $NEWRELIC_EU_WEST_STAGE_APPLICATION
    on:
      branch: master
      repo: mozilla/snippets-service
  - provider: script
    script: bin/deploy-travis.sh $DEIS_CONTROLLER_US_WEST $DEIS_PROD_ADMIN_APPLICATION $NEWRELIC_US_WEST_ADMIN_APPLICATION
    on:
      tags: true
      repo: mozilla/snippets-service
  - provider: script
    script: bin/deploy-travis.sh $DEIS_CONTROLLER_US_WEST $DEIS_PROD_APPLICATION $NEWRELIC_US_WEST_PROD_APPLICATION
    on:
      tags: true
      repo: mozilla/snippets-service
  - provider: script
    script: bin/deploy-travis.sh $DEIS_CONTROLLER_EU_WEST $DEIS_PROD_APPLICATION $NEWRELIC_EU_WEST_PROD_APPLICATION
    on:
      tags: true
      repo: mozilla/snippets-service
